// required to disable StyleCop
// <auto-generated>
using Tizen.Applications;
using Uno.UI.Runtime.Skia;

namespace UnoSamples.Skia.Tizen
{
    class Program
    {
        static void Main(string[] args)
        {
            var host = new TizenHost(() => new UnoSamples.App(), args);
            host.Run();
        }
    }
}
